version: '2'
services:
  agenda-app:
    image: agenda
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@agenda-oracle:1521:agenda
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
      - SPRING_DATA_JEST_URI=http://agenda-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://agenda-elasticsearch:9200
    ports:
      - 8080:8080
  agenda-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: agenda-elasticsearch
